import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';import {schema,service,CURRENT_SEASON,SEASONS,visibleSeasons} from '../server/ranking.js';import {voyageStage,SKY_PROTOCOL} from '../src/sky-voyage.js';
import {RankingClient,OUTBOX} from '../src/ranking.js';import {HIDDEN_NAME} from '../src/name-filter.js';import {normalize,freshSlot} from '../src/save.js';
const store=()=>{const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)}};
test('real SQL: seeded goals, seasons, goal order, duplicates, concurrent targets, finalization and snapshot records',async()=>{
 const db=new PGlite();try{for(const sql of schema)await db.exec(sql);const query=async(s,p)=>(await db.query(s,p)).rows,api=service(query),key='a'.repeat(64);
 const uid=(await api('register',{completed:true},key)).uid;assert.equal((await api('register',{completed:true},key)).uid,uid);await assert.rejects(api('register',{completed:false},'b'.repeat(64)),/LOCKED/);
 const status=await api('status');assert.equal(status.protocol,SKY_PROTOCOL);assert.equal(status.season.id,CURRENT_SEASON.id);assert.equal(status.seasons.length,visibleSeasons().length);assert(status.seasons.every(s=>!SEASONS.find(x=>x.id===s.id).hidden));
 await assert.rejects(api('start',{runId:randomUUID(),name:'古い版',design:{},protocol:1},key),/VERSION/);
 await assert.rejects(api('start',{runId:randomUUID(),name:'ちんちん号',design:{},protocol:SKY_PROTOCOL},key),/NAME/);await assert.rejects(api('start',{runId:randomUUID(),name:'090-1234-5678',design:{},protocol:SKY_PROTOCOL},key),/NAME/);
 const runId=randomUUID(),design={paint:2,wing:1,propeller:2,decoration:1};const started=await api('start',{runId,name:'そらいろ号',design,protocol:SKY_PROTOCOL},key);
 assert.equal(started.protocol,SKY_PROTOCOL);assert(Number.isInteger(started.seed)&&started.seed>=0);assert.equal(started.season.id,CURRENT_SEASON.id);
 assert.equal((await api('start',{runId,name:'そらいろ号',design,protocol:SKY_PROTOCOL},key)).seed,started.seed);
 const goal=level=>voyageStage(started.seed,level).target;
 assert.deepEqual(await api('standing',{},key),{season:{id:CURRENT_SEASON.id,name:CURRENT_SEASON.name,protocol:SKY_PROTOCOL,current:true},rank:null,distance:0});await assert.rejects(api('standing',{},'f'.repeat(64)),/AUTH/);
 await assert.rejects(api('goal',{runId,seq:1,level:0,target:goal(0)},'f'.repeat(64)),/AUTH/);
 const fresh=randomUUID();const s2=await api('start',{runId:fresh,name:'そらいろ号',design,protocol:SKY_PROTOCOL},key);const g2=level=>voyageStage(s2.seed,level).target;
 for(const e of [{seq:1,level:0,target:g2(0)},{seq:1,level:0,target:g2(0)},{seq:2,level:0,target:g2(0)},{seq:3,level:2,target:g2(2)}])await api('goal',{runId:fresh,...e},key);const total=g2(0)*2+g2(2);
 assert.equal((await api('board')).entries.length,0);
 await api('finish',{runId:fresh,count:3,distance:total,reason:'return'},key);await api('finish',{runId:fresh,count:3,distance:total,reason:'return'},key);
 let board=await api('board');let row=board.entries[0];assert.equal(board.season.id,CURRENT_SEASON.id);assert.equal((await api('standing',{},key)).rank,1);assert.equal((await api('standing',{},key)).distance,total);assert.equal(row.distance,total);assert.equal(row.name,'そらいろ号');assert.deepEqual(row.design,design);assert(!('key'in row));assert(!('secret_hash'in row));assert(!('seed'in row));assert(!('season'in row));
 // Season 1 keeps its records but is hidden: not listed, not readable, never written by the new protocol.
 await query('INSERT INTO mm_bests(uid,distance,snapshot) VALUES($1,777,$2::jsonb)',[uid,JSON.stringify({name:'むかしの機体',design})]);assert(SEASONS[0].hidden);await assert.rejects(api('board',{season:1}),/SEASON/);assert(!(await api('board')).seasons.some(s=>s.id===1));assert.equal((await query('SELECT count(*)::int AS n FROM mm_bests',[]))[0].n,1);await assert.rejects(api('board',{season:99}),/SEASON/);assert.equal((await api('board',{season:''})).season.id,CURRENT_SEASON.id);
 // A stored name that fails the current screening is masked on the board without touching the record.
 const masked=(await api('register',{completed:true},'c'.repeat(64))).uid;await query('INSERT INTO mm_season_bests(season,uid,distance,snapshot) VALUES($1,$2,1,$3::jsonb)',[CURRENT_SEASON.id,masked,JSON.stringify({name:'ｾｯｸｽ号',design:{}})]);assert.equal((await api('board')).entries.find(e=>e.uid===masked).name,HIDDEN_NAME);await query('DELETE FROM mm_season_bests WHERE uid=$1',[masked]);
 const other=(await api('register',{completed:true},'b'.repeat(64))).uid;await query('INSERT INTO mm_season_bests(season,uid,distance,snapshot) VALUES($1,$2,99999999,$3::jsonb)',[CURRENT_SEASON.id,other,JSON.stringify({name:'上位の機体',design:{}})]);assert.equal((await api('standing',{},key)).rank,2);await query('DELETE FROM mm_season_bests WHERE uid=$1',[other]);
 const shorter=randomUUID();const s3=await api('start',{runId:shorter,name:'別の名前',design:{},protocol:SKY_PROTOCOL},key);const g3=voyageStage(s3.seed,0).target;await api('goal',{runId:shorter,seq:1,level:0,target:g3},key);await api('finish',{runId:shorter,count:1,distance:g3,reason:'steam'},key);assert.equal((await api('board')).entries[0].name,'そらいろ号');
 const bad=randomUUID();await api('start',{runId:bad,name:'不正',protocol:SKY_PROTOCOL},key);await assert.rejects(api('goal',{runId:bad,seq:1,level:0,target:9999999},key),/INVALID/);await assert.rejects(api('finish',{runId:bad,count:0,distance:0,reason:'return'},key),/INVALID/);assert.equal((await api('board')).entries[0].distance,total);
 const missed=randomUUID();const s4=await api('start',{runId:missed,name:'未完了',protocol:SKY_PROTOCOL},key);await assert.rejects(api('goal',{runId:missed,seq:2,level:1,target:voyageStage(s4.seed,1).target},key),/INVALID/);
 const inflated=randomUUID();await api('start',{runId:inflated,name:'水増し',protocol:SKY_PROTOCOL},key);await assert.rejects(api('finish',{runId:inflated,count:0,distance:999,reason:'return'},key),/INVALID/);
 // A voyage whose seed sequence differs from what the server issued is rejected.
 const forged=randomUUID();const s5=await api('start',{runId:forged,name:'別シード',protocol:SKY_PROTOCOL},key);let wrong=voyageStage((s5.seed+1)>>>0,0).target;if(wrong===voyageStage(s5.seed,0).target)wrong+=1;await assert.rejects(api('goal',{runId:forged,seq:1,level:0,target:wrong},key),/INVALID/);
 }finally{await db.close()}
});
test('goal queue never waits for network; final notification follows all acks and survives reload',async()=>{
 const storage=store(),calls=[];let release;const gate=new Promise(r=>release=r);let held=true;
 const request=async(url,options)=>{const action=new URL(url,'https://game.test').searchParams.get('action');calls.push(action);if(action==='goal'&&held){held=false;await gate}return {ok:true,json:async()=>action==='register'?{uid:randomUUID()}:action==='start'?{runId:'x',protocol:SKY_PROTOCOL,seed:42,season:{id:2}}:{}}};
 const client=new RankingClient({storage,request}),s={...freshSlot(),cleared:Array.from({length:30},(_,i)=>i),flightName:'テスト号'};const run=await client.begin(s,()=>true);assert.equal(run.seed,42);assert.equal(run.season,2);
 client.goal(run,0,81);client.goal(run,1,108);client.finish(run,'return');assert.equal(run.count,2);assert.equal(run.distance,189);assert.equal(run.events.length,3);assert(!calls.includes('finish'));const snapshot=storage.getItem(OUTBOX);release();while(client.running)await new Promise(r=>setTimeout(r,5));assert.equal(run.status,'finished');assert.deepEqual(calls.slice(-3),['goal','goal','finish']);
 storage.setItem(OUTBOX,snapshot);const restarted=new RankingClient({storage,request});await restarted.flush();assert.equal(restarted.runs[0].status,'finished');assert.equal(restarted.runs[0].distance,189);
});
test('invalid online record is isolated from saves; offline retries retain queued goals',async()=>{
 const storage=store(),client=new RankingClient({storage,request:async()=>({ok:false,status:409,json:async()=>({error:'INVALID'})})});const run={runId:randomUUID(),key:'a'.repeat(64),events:[],count:0,distance:0,status:'flying',closed:false};client.runs.push(run);client.goal(run,0,81);while(client.running)await new Promise(r=>setTimeout(r,5));assert.equal(run.status,'excluded');
 const offline=new RankingClient({storage:store(),request:async()=>{throw new TypeError('offline')}});const r={...run,events:[],count:0,distance:0,status:'flying'};offline.runs.push(r);offline.goal(r,0,81);while(offline.running)await new Promise(r=>setTimeout(r,5));clearTimeout(offline.timer);assert.equal(r.events.length,1);assert.equal(r.status,'flying');
});
test('name and per-save identity survive normalization without touching old progress',()=>{const s={...freshSlot(),cleared:[0,1,2],flightName:'そらいろ号',ranking:{key:'a'.repeat(64),uid:randomUUID()},sky:{total:1234,best:999,flights:2}};const n=normalize({version:1,slots:[s,null,null],settings:{sound:false,slow:true},bests:{'score-add':111}});assert.equal(n.slots[0].flightName,s.flightName);assert.deepEqual(n.slots[0].ranking,s.ranking);assert.deepEqual(n.slots[0].cleared,s.cleared);assert.equal(n.slots[0].sky.total,1234);assert.equal(n.bests['score-add'],111);assert.equal(n.slots[1],null)});
test('production API loads safely without a database and returns a setup status',async()=>{const {default:handler}=await import('../api/ranking.js');const old=process.env.DATABASE_URL,oldPostgres=process.env.POSTGRES_URL;delete process.env.DATABASE_URL;delete process.env.POSTGRES_URL;try{let code,body;const res={setHeader(){},status(n){code=n;return this},json(v){body=v}};await handler({url:'/api/ranking?action=status',method:'GET',headers:{}},res);assert.equal(code,503);assert.deepEqual(body,{error:'NOT_CONFIGURED'});}finally{if(old!==undefined)process.env.DATABASE_URL=old;if(oldPostgres!==undefined)process.env.POSTGRES_URL=oldPostgres;}});
