import test from 'node:test';import assert from 'node:assert/strict';
import {voyageStage,voyageEvaluate,voyageSolution,prepareVoyageBoard,voyageUnlocked,voyageRecord,addDistance} from '../src/sky-voyage.js';
import {freshSlot,normalize} from '../src/save.js';import {stageBrief} from '../src/stage-intro.js';
test('sky routes start at 81, rise to four factors, and always offer a legal path',()=>{
 assert.equal(voyageStage().target,81);let previous=0;
 for(let i=0;i<35;i++){const t=voyageStage(i),b=prepareVoyageBoard(Array(25).fill(2),t),s=voyageSolution(b,t.target);assert(s);assert(s.path.length>=2&&s.path.length<=4);assert.equal(voyageEvaluate(b,s.path,'×',t.target).kind,'success');assert(b.every(n=>n>=2&&n<=9));if(i<12){assert(t.target>previous);previous=t.target}if(i>=7)assert.equal(t.factors.length,4);}
});
test('sky uses ordinary matching rules, including two-stone 9 × 9 and addition',()=>{const b=Array(25).fill(3);b[0]=b[1]=9;assert.equal(voyageEvaluate(b,[0,1],'×',81).kind,'success');assert.equal(voyageEvaluate(b,[2,3,4],'+',9).kind,'success');assert.equal(voyageEvaluate(b,[2,3],'+',81).kind,'merge');b[2]=9;assert.equal(voyageEvaluate(b,[0,1,2],'×',81).kind,'clear');assert.equal(voyageEvaluate(b,[2,3,4],'×',81).kind,'success')});
test('old saves preserve all slots and designs; only all 30 clears unlock the voyage',()=>{const slots=[{...freshSlot(),cleared:Array.from({length:30},(_,i)=>i),paint:2,wing:1,propeller:2,decoration:1,updated:123},{...freshSlot(),cleared:[0,1,29]},null];slots.forEach(s=>{if(s)delete s.sky});const old={version:1,slots,settings:{sound:false,slow:true},bests:{'endless-mix':1234}};const n=normalize(old);assert(voyageUnlocked(n.slots[0]));assert(!voyageUnlocked(n.slots[1]));assert(!voyageUnlocked(n.slots[2]));n.slots.forEach((s,i)=>{if(s){const {sky,...rest}=s;assert.deepEqual(rest,slots[i]);assert.deepEqual(sky,voyageRecord())}else assert.equal(slots[i],null)});assert.deepEqual(n.settings,old.settings);assert.deepEqual(n.bests,old.bests)});
test('distance and treasure progress persist across flights without reducing best',()=>{let r=voyageRecord(),run=0;for(const n of [81,108,144,216]){run+=n;r=addDistance(r,n,run)}assert.equal(r.total,549);assert.equal(r.best,549);assert.deepEqual(r.treasures,[0]);r=addDistance(r,81,81);assert.equal(r.total,630);assert.equal(r.best,549);assert.deepEqual(voyageRecord(r),r);assert.deepEqual(voyageRecord({total:-1,best:Infinity,flights:'2',treasures:[5]}),voyageRecord());assert.deepEqual(voyageRecord({total:150000,best:999999}).treasures,[0,1,2,3,4,5])});
test('sky intro explains distance and multiplication without an infinite count',()=>{const b=stageBrief(voyageStage(),{mode:'sky'});assert.equal(b.target,81);assert.equal(b.label,'SECRET CHAPTER 06');assert.match(b.hint,/＋と×/);assert(!b.hint.includes('3枚'));assert(!JSON.stringify(b).includes('Infinity'))});

test('hints accept adjacent nines without replacing the board',()=>{const b=Array(25).fill(2);b[0]=b[1]=9;assert.deepEqual(voyageSolution(b,81),{path:[0,1],op:'×'});assert.equal(prepareVoyageBoard(b,voyageStage()),b);assert.equal(voyageEvaluate(b,[0],'×',81).kind,'cancel')});
