import {victoryEffects} from './celebration.js';
import {showStageIntro} from './stage-intro.js';
import {Soundtrack,creditsHTML} from './soundtrack.js';
import {planeArt,partArt,collectedParts,assemblyLevel,assemblyNames,collectionStrip,customizationOptions,canCustomize} from './airplane.js';
import {showChapterScene} from './chapter-scenes.js';
import {showDialogue} from './dialogue.js';
import {prologue,stageStory,epilogue} from './story.js';
import {requestInstall} from './pwa.js';
import {chapters,stages,hints,palette} from './data.js';
import {extend,total,evaluate,resolve,solution,createBoard} from './engine.js';
import {load,save,freshSlot} from './save.js';
const app=document.querySelector('#app'), dialog=document.querySelector('#dialog');
let data=load(),slot=0,screen='title',game=null,pointer=null,last=performance.now(),toastTimer,pendingDelete=null;
const soundtrack=new Soundtrack(data.settings.sound);
const $=s=>document.querySelector(s);
const button=(text,action,cls='')=>`<button class="${cls}" data-action="${action}">${text}</button>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){if(!save(data))toast('このブラウザでは保存できません。通常のブラウザで開いてね。');}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function modal(title,body,actions){soundtrack.duck('dialog',true);pendingDelete=null;if(game)game.paused=true;pointer=null;dialog.innerHTML=`<div class="dialog-inner"><p class="eyebrow">MIRACLE MINE</p><h2>${title}</h2>${body}<div class="dialog-actions">${actions}</div></div>`;dialog.classList.toggle('victory-dialog',!!dialog.querySelector('.victory-effects'));if(!dialog.open)dialog.showModal();}
function closeModal(resume=true){soundtrack.duck('dialog',false);pendingDelete=null;dialog.close();if(game&&resume&&!game.over)game.paused=false;last=performance.now();}
function chrome(title,back='title'){return `<header>${button('‹ 戻る',back,'subtle')}<div><small>MIRACLE MINE</small><h2>${title}</h2></div>${button(menuIcon(4)+'設定','settings','subtle')}</header>`;}
function setScreen(name){if(name!=='game')soundtrack.duck('result',false);soundtrack.setScene(name);screen=name;document.body.dataset.screen=name;document.body.dataset.chapter=game?.stage.chapter??0;}
const menuIcon=n=>`<i class="menu-art" aria-hidden="true" style="--icon-x:${n%3*50}%;--icon-y:${Math.floor(n/3)*100}%"></i>`;
function title(){game=null;closeModal(false);setScreen('title');app.innerHTML=`<section class="title-screen illustrated-title">${button('音楽を再生','music-toggle','title-audio subtle')}<div class="title-copy"><div class="title-masthead"><p class="eyebrow">数字がつながる、せかいがひろがる</p><h1 class="title-logo"><img src="/assets/title-logo.webp" alt="Miracle Mine" width="1536" height="1024" fetchpriority="high"></h1><p class="kana">ミラクルマイン</p></div><div class="title-portrait-scene" role="img" aria-label="ルカとトトじい、モスが蒸気飛行機と一緒に冒険へ出発する工房"></div><nav class="main-menu" aria-label="ゲームモード">${button(menuIcon(0)+'ストーリーモード','slots')}${button(menuIcon(1)+'スコアアタック','challenge:score')}${button(menuIcon(2)+'エンドレス','challenge:endless')}</nav></div><div class="title-bottom"><p class="title-tag">小さな数字で、大きな冒険へ。</p>${button(menuIcon(3)+'あそびかた','help','subtle')}${button(menuIcon(5)+'ホーム画面に追加','install','subtle install-button')}${button(menuIcon(4)+'設定','settings','subtle')}<span>PROTOTYPE 0.10</span></div></section>`;updateMusicButton();}

function slots(){game=null;closeModal(false);setScreen('slots');app.innerHTML=`<section class="page">${chrome('冒険の記録')}<p class="intro">きみの工房をえらぼう</p><div class="slot-grid">${data.slots.map((s,i)=>{const parts=collectedParts(s),level=assemblyLevel(parts);return `<article class="save-slot"><button class="slot parchment visual-slot" data-action="slot:${i}"><span class="slot-heading"><small>LOGBOOK ${String(i+1).padStart(2,'0')}</small><span class="slot-number">${['Ⅰ','Ⅱ','Ⅲ'][i]}</span></span><span class="slot-airplane ${s?'':'unstarted'}">${planeArt(level,s||{})}</span><h3>${s?assemblyNames[level]:'新しい冒険'}</h3><span class="slot-progress">${s?`${s.cleared.length} / 30 ステージ · ${parts.length} / 5 部品`:'ルカと、ここから空をめざそう'}</span>${collectionStrip(parts)}<span class="slot-foot">${s?'つづきから · 工房をひらく →':'はじめる →'}</span></button>${s?`<button class="slot-delete" data-action="delete-slot:${i}" aria-label="工房 ${i+1} のセーブデータを消す">データを消す</button>`:''}</article>`;}).join('')}</div><p class="muted">記録は、この端末のブラウザに自動保存されます。</p></section>`;}
function requestDeleteSlot(i){
 if(screen!=='slots'||!Number.isInteger(i)||i<0||i>=3)return;
 data=load();const record=data.slots[i];if(!record){slots();return;}
 const parts=chapters.filter((_,ci)=>record.cleared.includes(ci*6+5)).length;
 modal(`工房 ${i+1} のデータを消す？`,`<p class="delete-slot-summary">${record.cleared.length} / 30 ステージクリア<br>${parts} / 5 部品を獲得</p><p>この工房の冒険の記録と、飛行機のデザインを消します。<br><strong>消したデータは元に戻せません。</strong></p><p class="muted">ほかの工房の記録、ハイスコア、設定は残ります。</p><p class="delete-slot-error" role="alert" hidden></p>`,button('やめる','close','primary')+button('このデータを消す','confirm-delete-slot','danger-button'));
 pendingDelete={index:i,snapshot:JSON.stringify(record)};
 dialog.querySelector('[data-action="close"]').focus();
}
function deleteSlot(){
 if(screen!=='slots'||!dialog.open||!pendingDelete)return;
 const {index,snapshot}=pendingDelete,latest=load();
 if(JSON.stringify(latest.slots[index])!==snapshot){data=latest;slots();toast('記録が更新されています。消すデータをもう一度確認してね。');return;}
 const next={...latest,slots:latest.slots.map((record,i)=>i===index?null:record)};
 if(!save(next)){const error=dialog.querySelector('.delete-slot-error');error.hidden=false;error.textContent='データを消せませんでした。ブラウザの保存設定を確認してね。';return;}
 data=next;slots();toast(`工房 ${index+1} のデータを消しました`);
 app.querySelector(`[data-action="slot:${index}"]`).focus();
}
function openSlot(i){slot=i;if(!data.slots[slot]){data.slots[slot]=freshSlot();persist();map();conversation(prologue);}else{map();const next=stages.find(t=>!data.slots[slot].cleared.includes(t.id))||stages[29];showChapterScene(next.chapter,{resume:true,onNext:()=>{}});}}
function conversation(story,done=()=>{}){const g=game;if(g)g.paused=true;pointer=null;soundtrack.duck('story',true);showDialogue(story,()=>{soundtrack.duck('story',false);last=performance.now();if(game===g&&g&&!g.over)g.paused=false;done();});}
function unlocked(i){return i===0||data.slots[slot]?.cleared.includes(i-1);}
const chapterIcon=n=>`<i class="chapter-art" aria-hidden="true" style="--icon-x:${n%3*50}%;--icon-y:${Math.floor(n/3)*100}%"></i>`;
function map(){game=null;closeModal(false);setScreen('map');const s=data.slots[slot];app.innerHTML=`<section class="page map-page">${chrome(`工房 ${slot+1} · 冒険の地図`,'slots')}<div class="map-heading"><div><p class="eyebrow">THE JOURNEY TO THE SKY</p><h3>素材をあつめて、空へ。</h3></div><div>${button('はじまりの物語','prologue','subtle')}${button(chapterIcon(5)+'蒸気飛行機の工房','workshop','primary')}</div></div><div class="chapter-list">${chapters.map((c,ci)=>`<article class="chapter parchment" style="--chapter-color:${c.color}"><div class="chapter-info">${chapterIcon(ci)}<div><small>CHAPTER ${ci+1} / ${c.tag}</small><h3>${c.name}</h3><p>${c.part} · ${s.cleared.includes(ci*6+5)?'獲得済み':'素材を探そう'}</p></div></div><div class="stage-list">${stages.slice(ci*6,ci*6+6).map(t=>`<button data-action="stage:${t.id}" ${!unlocked(t.id)?'disabled':''} class="stage ${s.cleared.includes(t.id)?'cleared':''} ${unlocked(t.id)&&!s.cleared.includes(t.id)?'next':''}" aria-label="${ci+1}-${t.step+1} ${t.name} 目標${t.target}"><b>${unlocked(t.id)?`${ci+1}-${t.step+1}`:'⌑'}</b><small>${s.cleared.includes(t.id)?'✓':`${t.target} をつくる`}</small></button>`).join('')}</div></article>`).join('')}</div><p class="muted">${s.cleared.length} / 30 ステージクリア · 好きなステージをもう一度遊べます</p></section>`;}
function workshop(){game=null;closeModal(false);setScreen('workshop');const s=data.slots[slot],owned=collectedParts(s),level=assemblyLevel(owned),parts=owned.length;const paints=['青緑','夕焼け','夜空'];app.innerHTML=`<section class="page rich-workshop">${chrome('きみだけの蒸気飛行機','map')}<div class="hangar-layout"><div class="hangar-main parchment"><div class="hangar-heading"><div><p class="eyebrow">LUKA’S STEAM AIRPLANE</p><h2>${assemblyNames[level]}</h2></div><span class="build-count">${parts}<small> / 5 部品</small></span></div><div class="hangar-display">${planeArt(level,s)}<span class="hangar-badge">工房 ${slot+1} · ${paints[s.paint]}の機体</span></div>${customizationPanel(s)}<div class="assembly-steps" aria-label="組み立ての進み具合">${assemblyNames.map((name,i)=>`<span class="${i<=level?'reached':''} ${i===level?'current':''}" title="${name}">${i===0?'START':i===5?'FLIGHT':String(i).padStart(2,'0')}</span>`).join('')}</div><p class="hangar-next">${level===5?'みんなの力を乗せて、雲の向こうへ。':`次は「${chapters[level].name}」で、${chapters[level].part}を集めよう。`}</p><div class="hangar-actions">${button(level===5?'✦ おじいちゃんと初飛行':'素材を探しにいく',level===5?'flight':'map','primary')}${button('組み立てを振り返る','assembly-replay','subtle')}</div></div><div class="hangar-inventory parchment"><p class="eyebrow">COLLECTION LOG</p><h3>冒険であつめた部品</h3>${chapters.map((c,i)=>`<div class="inventory-card ${owned.includes(i)?'owned':'missing'}">${partArt(i)}<div><small>第${i+1}章 · ${c.name}</small><strong>${c.part}</strong><span>${owned.includes(i)?'✓ 組み立て済み':`未獲得 · ${c.material}`}</span></div></div>`).join('')}</div></div></section>`;}
function customizationPanel(s){return `<div class="hangar-custom"><h3>飛行機のデザイン</h3><div class="custom-grid">${customizationOptions.map(o=>`<fieldset ${canCustomize(s,o.key)?'':'disabled'}><legend>${o.label}${canCustomize(s,o.key)?'':` · 第${o.part+1}章の部品で解放`}</legend><div class="choices">${o.options.map((label,n)=>`<button data-action="custom:${o.key}:${n}" class="${s[o.key]===n?'active':''}" aria-pressed="${s[o.key]===n}">${label}</button>`).join('')}</div></fieldset>`).join('')}</div><p class="custom-feedback" role="status" aria-live="polite">パーツを選ぶと、上の機体に反映されます。</p></div>`;}
function changeDesign(key,value){
 const s=data.slots[slot];if(screen!=='workshop'||!s||!canCustomize(s,key)||!Number.isInteger(value)||value<0||value>2)return;
 const next={...s,[key]:value,updated:Date.now()},nextData={...data,slots:data.slots.map((record,i)=>i===slot?next:record)};
 if(!save(nextData)){toast('デザインを保存できませんでした。もう一度試してね。');return;}data=nextData;soundtrack.play('assemble');
 const level=assemblyLevel(collectedParts(next));document.querySelector('.hangar-display .airplane-render').outerHTML=planeArt(level,next);
 const option=customizationOptions.find(o=>o.key===key);document.querySelectorAll(`[data-action^="custom:${key}:"]`).forEach(el=>{const selected=el.dataset.action===`custom:${key}:${value}`;el.classList.toggle('active',selected);el.setAttribute('aria-pressed',String(selected));});
 document.querySelector('.hangar-badge').textContent=`工房 ${slot+1} · ${customizationOptions[0].options[next.paint]}の機体`;
 document.querySelector('.custom-feedback').textContent=`${option.label}を「${option.options[value]}」にしました。保存済み！`;
}
function replayAssembly(){const s=data.slots[slot],owned=collectedParts(s);let i=0;const advance=()=>{while(i<5&&!owned.includes(i))i++;if(i===5){workshop();return;}const index=i++;showChapterScene(index,{clear:true,completed:owned.filter(n=>n<=index),previous:owned.filter(n=>n<index),paint:s.paint,design:s,onNext:advance,onMap:workshop});};if(!owned.length){toast('最初の部品を集めたら、組み立てを見られるよ。');return;}advance();}
function challenge(mode){modal(mode==='score'?'スコアアタック':'エンドレス',`<p>${mode==='score'?'3分間で、どれだけエネルギーを集められる？':'ライフが続くかぎり、どこまでも。'}</p><p>「ミックス」では掛け算も使えるよ。</p><div class="best-list">足し算 BEST ${data.bests[mode+'-add']||0}<br>ミックス BEST ${data.bests[mode+'-mix']||0}</div>`,button('足し算で遊ぶ',`start:${mode}:add`,'primary')+button('ミックスで遊ぶ',`start:${mode}:mix`)+button('戻る','close','subtle'));}
function challengeStage(g){const pool=g.variant==='mix'?[stages[12],stages[18],stages[20],stages[21],stages[22],stages[28]]:[stages[0],stages[6],stages[12]];const t=pool[Math.min(Math.floor(g.done/5),pool.length-1)];return {...t,min:0,life:60,recover:9,count:Infinity,multiply:g.variant==='mix'};}
function briefStage(g,resume=false){if(game!==g||g.over)return;g.paused=true;pointer=null;showStageIntro(g.stage,{mode:g.mode,resume,remaining:g.stage.count-g.done,onStart:()=>{if(game!==g||g.over)return;g.paused=false;last=performance.now();}});}
function start(mode,id=0,variant='add'){soundtrack.duck('result',false);closeModal(false);game={mode,variant,stage:stages[id],path:[],op:'+',done:0,score:0,combo:0,paused:false,over:false,life:0,remaining:180,board:[],busy:false,hint:[],message:'数字をつないでみよう',failures:0};if(mode!=='story')game.stage=challengeStage(game);game.life=game.stage.life;game.board=createBoard(game.stage);setScreen('game');renderGame();last=performance.now();if(mode==='story'){game.paused=true;const g=game;const begin=()=>conversation(stageStory(g.stage),()=>briefStage(g));if(game.stage.step===0)showChapterScene(game.stage.chapter,{onNext:begin});else begin();return;}briefStage(game);}
const tileCoords=[ [51,177],[347,177],[642,177],[937,177],[1232,177],[51,549],[347,549],[642,549],[937,549],[1232,549] ];
function tileStyle(n){const [x,y]=tileCoords[n];return `--stone:${palette[n]};background-size:${1553/260*100}% ${1013/285*100}%;background-position:${x/(1553-260)*100}% ${y/(1013-285)*100}%;`;}
function renderGame(){const g=game,c=chapters[g.stage.chapter];app.innerHTML=`<section class="game-screen"><aside class="mission"><div class="stage-sign parchment"><small>${g.mode==='story'?`STAGE ${g.stage.chapter+1}-${g.stage.step+1}`:g.mode==='score'?'SCORE ATTACK':'ENDLESS'}</small><h2>${c.name}</h2></div><div class="target-medal"><small>お題</small><strong id="target">${g.stage.target}</strong><span>をつくろう！</span></div><div class="progress-card parchment"><span>${g.mode==='story'?'できた数':'スコア'}</span><b id="progress">0 / ${g.stage.count}</b></div><div class="guardian-card"><div class="guardian guardian-${g.stage.chapter}" role="img" aria-label="${c.guardian}"></div><div class="speech" id="guardian-text">力をかしてくれる？</div></div><div class="reward parchment"><small>${g.mode==='story'?'ごほうび':'ハイスコア'}</small><b>${g.mode==='story'?c.material:data.bests[g.mode+'-'+g.variant]||0}</b></div></aside><div class="puzzle"><div id="board" class="board" role="group" aria-label="数字の盤面。ドラッグ、または数字を選んで確定。">${g.board.map((n,i)=>`<button class="stone" data-index="${i}" style="${tileStyle(n)}" aria-label="${n}、${Math.floor(i/5)+1}行${i%5+1}列"><span class="sr-only">${n}</span></button>`).join('')}<svg id="trace" viewBox="0 0 500 500" aria-hidden="true"><polyline class="trace-shadow"/><polyline class="trace-line"/></svg></div><div class="equation parchment" aria-live="polite"><strong id="equation">数字をなぞろう</strong><small id="outcome">上下・左右・ななめにつながるよ</small></div><div class="puzzle-actions">${button('取り消す','cancel','subtle')}${button('確定する ↵','confirm','subtle')}</div></div><aside class="game-side"><div class="game-toolbar">${button('？','help','icon-button')}${button('Ⅱ','pause','icon-button')}</div><div class="boiler parchment"><label>${g.mode==='score'?'残り時間':'ライフ'} <span id="time-label"></span></label><div class="life-track"><div id="life-fill"></div></div><small id="combo">いい調子でいこう！</small></div><div class="advice speech" id="message">${g.stage.multiply?'足して準備、掛けて完成！':'小さな数は、まとめよう！'}</div><div class="luka-portrait" role="img" aria-label="ルカ"></div><div class="operation"><button data-action="op:+" class="op active" aria-label="足し算">＋</button><button data-action="op:×" class="op" ${g.stage.multiply?'':'disabled'} aria-label="掛け算${g.stage.multiply?'':'、火山の章で解放'}">×${g.stage.multiply?'':'<small>火山で解放</small>'}</button></div><div class="side-actions">${button('ひらめき','hint','subtle')}${button('並べなおす','shuffle','subtle')}</div></aside></section>`;wireBoard();updateHUD();}
function updateBoard(){if(!game||screen!=='game')return;document.querySelectorAll('.stone').forEach((el,i)=>{const n=game.board[i];el.style.cssText=tileStyle(n);el.setAttribute('aria-label',`${n}、${Math.floor(i/5)+1}行${i%5+1}列`);el.firstElementChild.textContent=n;});updateSelection();}
function updateSelection(){const g=game;if(!g||screen!=='game')return;document.querySelectorAll('.stone').forEach((el,i)=>{el.classList.toggle('selected',g.path.includes(i));el.classList.toggle('hinted',g.hint.includes(i));el.setAttribute('aria-pressed',String(g.path.includes(i)));});const points=g.path.map(i=>`${(i%5)*100+50},${Math.floor(i/5)*100+50}`).join(' ');$('#trace').querySelectorAll('polyline').forEach(p=>p.setAttribute('points',points));if(!g.path.length){$('#equation').textContent='数字をなぞろう';$('#outcome').textContent=g.message;return;}const value=total(g.board,g.path,g.op);$('#equation').textContent=g.path.map(i=>g.board[i]).join(` ${g.op} `)+` = ${value}`;const kind=evaluate(g.board,g.path,g.op,g.stage.target).kind;$('#outcome').textContent=g.path.length<2?'もうひとつ、つないでみよう':kind==='success'?'ぴったり！ はなすと完成':kind==='merge'?`はなすと「${value}」に合体`:'石を消して整理（ライフ回復なし）';}
function updateHUD(){if(!game||screen!=='game')return;const g=game;$('#progress').textContent=g.mode==='story'?`${g.done} / ${g.stage.count}`:g.score.toLocaleString();$('#target').textContent=g.stage.target;const ratio=g.mode==='score'?g.remaining/180:g.life/g.stage.life;$('#life-fill').style.width=`${Math.max(0,ratio)*100}%`;$('#life-fill').classList.toggle('low',ratio<.25);$('#time-label').textContent=g.mode==='score'?`${Math.floor(Math.ceil(g.remaining)/60)}:${String(Math.ceil(g.remaining)%60).padStart(2,'0')}`:`${Math.ceil(g.life)}s`;$('#combo').textContent=g.combo>1?`${g.combo}連続成功！`:'ゆっくり考えてみよう';$('#guardian-text').textContent=g.mode==='story'?`あと${g.stage.count-g.done}こ、お願い！`:`${g.done}こ完成！`;document.querySelectorAll('.op').forEach(el=>el.classList.toggle('active',el.dataset.action==='op:'+g.op));}
function canPlay(){return game&&!game.paused&&!game.busy&&!game.over&&screen==='game';}
function pointIndex(x,y){const r=$('#board').getBoundingClientRect();const col=Math.floor((x-r.left)/r.width*5),row=Math.floor((y-r.top)/r.height*5);return x<r.left||x>=r.right||y<r.top||y>=r.bottom?-1:row*5+col;}
function addIndex(i){if(!canPlay()||i<0)return;const p=extend(game.path,i);if(p!==game.path){soundtrack.play(p.length>game.path.length?'select':'back');game.path=p;game.hint=[];updateSelection();}}
function wireBoard(){const b=$('#board');b.addEventListener('pointerdown',e=>{if(!canPlay()||pointer!==null||e.button!==0)return;const i=pointIndex(e.clientX,e.clientY);if(i<0)return;e.preventDefault();pointer=e.pointerId;b.setPointerCapture(pointer);if(game.path.length&&!game.path.includes(i)&&extend(game.path,i)===game.path)game.path=[];addIndex(i);});b.addEventListener('pointermove',e=>{if(pointer===e.pointerId&&canPlay())addIndex(pointIndex(e.clientX,e.clientY));});b.addEventListener('pointerup',e=>{if(pointer!==e.pointerId)return;pointer=null;if(game.path.length>=2)commit();});b.addEventListener('pointercancel',()=>{pointer=null;if(game){game.path=[];updateSelection();}});b.addEventListener('keydown',e=>{const i=Number(e.target.dataset.index);if(!Number.isInteger(i)||!canPlay())return;const offsets={ArrowRight:1,ArrowLeft:-1,ArrowUp:-5,ArrowDown:5};if(e.key in offsets){e.preventDefault();const n=i+offsets[e.key];if(n>=0&&n<25&&(!(e.key==='ArrowRight'||e.key==='ArrowLeft')||Math.floor(i/5)===Math.floor(n/5)))b.querySelector(`[data-index="${n}"]`).focus();}else if(e.key===' '){e.preventDefault();addIndex(i);}else if(e.key==='Enter'){e.preventDefault();if(game.path.length>=2)commit();else addIndex(i);}else if(e.key==='Escape'){game.path=[];updateSelection();}});}
async function commit(){if(!canPlay())return;const g=game,t=g.stage;const result=evaluate(g.board,g.path,g.op,t.target);if(result.kind==='cancel')return;g.busy=true;pointer=null;$('#board').classList.add(result.kind==='success'?'celebrate':'settling');soundtrack.play(result.kind==='success'?'success':result.kind==='merge'?'merge':'discard');const path=[...g.path];await new Promise(r=>setTimeout(r,240));if(game!==g||g.over)return;const spawn=()=>t.min+Math.floor(Math.random()*(t.max-t.min+1));g.board=resolve(g.board,path,g.op,t.target,spawn).board;g.path=[];g.hint=[];if(result.kind==='success'){g.done++;g.combo++;g.score+=100+Math.min(g.combo-1,10)*20;if(g.mode!=='score')g.life=Math.min(t.life,g.life+t.recover);g.message=`${result.value} 完成！ よくできた！`;}else if(result.kind==='merge'){g.message=`「${result.value}」に合体したよ`;}else{g.combo=0;g.message='石を整理したよ。次はお題をつくろう';}g.busy=false;$('#board').classList.remove('celebrate','settling');$('#message').textContent=g.message;updateBoard();updateHUD();if(g.mode==='story'&&g.done>=t.count){finish(true);return;}if(g.mode!=='story'&&result.kind==='success'&&g.done%5===0){g.stage=challengeStage(g);g.board=createBoard(g.stage);g.op='+';renderGame();toast(`次は ${g.stage.target} をつくろう！`);}}
function finish(win){const g=game;if(!g||g.over)return;g.over=true;g.paused=true;pointer=null;soundtrack.duck('result',true);soundtrack.play(win?(g.stage.step===5?'chapter':'clear'):'failure');if(g.mode==='story'){const s=data.slots[slot];if(win){const previous=collectedParts(s);if(!s.cleared.includes(g.stage.id))s.cleared.push(g.stage.id);s.failures=0;s.updated=Date.now();persist();const c=chapters[g.stage.chapter];const result=()=>modal(g.stage.id===29?'空へ、出発！':'ステージクリア！',`${victoryEffects()}<div class="result-medal" aria-hidden="true">✦</div><p class="victory-label">WONDERFUL!</p><p>${g.stage.step===5?c.end:'ありがとう！ もう少しで素材が集まりそうだよ。'}</p><h3>${g.stage.step===5?`${c.part} を手に入れた！`:`${g.stage.count}回、完成！`}</h3>`,g.stage.id===29?button('おじいちゃんと飛ぼう','flight','primary')+button('工房へ','workshop'):button('次へ',`stage:${g.stage.id+1}`,'primary')+button('冒険の地図へ','map'));if(g.stage.step===5){showChapterScene(g.stage.chapter,{clear:true,completed:collectedParts(s),previous,paint:s.paint,design:s,onNext:()=>g.stage.id===29?act('flight'):start('story',g.stage.id+1),onMap:map});}else result();}else{s.failures++;persist();modal('もう一度、やってみよう',`<p>集めた素材はなくならないよ。</p><p>${g.done} / ${g.stage.count} 回できたね。小さい石を合体させるのもコツだよ。</p>${s.failures>=2?'<p>設定で「ゆっくりライフ」にすると、考える時間が長くなるよ。</p>':''}`,button('もう一度',`stage:${g.stage.id}`,'primary')+button('ゆっくりで再挑戦',`slow-retry:${g.stage.id}`)+button('地図へ','map'));}}else{const key=g.mode+'-'+g.variant,record=g.score>(data.bests[key]||0);data.bests[key]=Math.max(g.score,data.bests[key]||0);persist();modal(g.mode==='score'?'タイムアップ！':'冒険の記録',`<p>${record?'NEW BEST!':'SCORE'}</p><div class="result-score">${g.score.toLocaleString()}</div><p>${g.done}こ完成 · ${g.variant==='mix'?'ミックス':'足し算'}</p>`,button('もう一度',`start:${g.mode}:${g.variant}`,'primary')+button('タイトルへ','title'));}}
function pause(){if(!game||game.over)return;game.path=[];updateSelection();modal('ひとやすみ',`<p>ライフと時間は止まっています。</p>`,button('つづける','resume-game','primary')+button('設定','settings')+button('冒険をやめる','quit','subtle'));}
function help(){modal('あそびかた',`<ol class="instructions"><li>となりあう数字を、上下・左右・ななめになぞろう。</li><li>お題と同じ数なら成功！ ストーリーとエンドレスはライフが回復。</li><li>お題より小さく、0〜9なら最後の場所に合体。</li><li>それ以外は石が消えるだけ。ライフは回復しないよ。</li><li>火山からは「×」も使える。6×6で36を作れるよ。</li></ol><p class="muted">PC：方向キーで移動、Spaceで石を選択、Enterで確定。ひとつ前に戻ると選択を取り消せます。</p>`,button('わかった！','close','primary'));}
function updateMusicButton(){const el=document.querySelector('[data-action="music-toggle"]');if(!el)return;const on=soundtrack.settings.music&&soundtrack.settings.musicVolume>0,playing=on&&soundtrack.unlocked&&soundtrack.context?.state==='running';el.textContent=playing?'音楽 ON':on?'音楽を再生':'音楽 OFF';el.setAttribute('aria-pressed',String(playing));el.setAttribute('aria-label',playing?'BGMをオフにする':'BGMを再生する');}
function settings(){const a=soundtrack.settings;modal('設定',`<div class="audio-settings"><div class="audio-setting"><label class="setting"><span>BGM</span><input type="checkbox" id="music" ${a.music?'checked':''}></label><label class="volume-setting" for="music-volume"><span>音楽の音量</span><output id="music-value">${Math.round(a.musicVolume*100)}%</output><input id="music-volume" type="range" min="0" max="100" step="5" value="${Math.round(a.musicVolume*100)}"></label></div><div class="audio-setting"><label class="setting"><span>効果音</span><input type="checkbox" id="sound" ${a.sound?'checked':''}></label><label class="volume-setting" for="sound-volume"><span>効果音の音量</span><output id="sound-value">${Math.round(a.soundVolume*100)}%</output><input id="sound-volume" type="range" min="0" max="100" step="5" value="${Math.round(a.soundVolume*100)}"></label></div></div><p class="audio-save-status muted" role="status">音の設定は変更すると保存されます。</p><label class="setting"><span>ゆっくりライフ<br><small>ストーリーだけ、減る速さを半分に</small></span><input type="checkbox" id="slow" ${data.settings.slow?'checked':''}></label>${creditsHTML}<p class="muted">冒険の記録は、このブラウザに保存されます。</p>`,button('保存して戻る','save-settings','primary')+button('全画面表示','fullscreen','subtle'));}

function flight(){game=null;closeModal(false);setScreen('flight');app.innerHTML=`<section class="flight-screen"><div class="parchment ending"><p class="eyebrow">A NEW HORIZON</p><h1>雲の、その先へ。</h1><p>「おじいちゃん、見て！ 新しい島だ！」</p><p>森の木、海の金属、洞窟の結晶。<br>みんなの力を乗せて、ルカの飛行機は空へ。</p><p>「さあ、次はどこへ行こうか」</p>${button('工房へ帰る','workshop','primary')}</div></section>`;}
function hint(){if(!canPlay())return;soundtrack.play('hint');const found=solution(game.board,game.stage.target,game.stage.multiply?['+','×']:['+']);if(found){game.hint=found.path;game.op=found.op;game.path=[];game.message=`${found.op} で、光る石をつないでみよう`;updateSelection();updateHUD();$('#message').textContent=game.message;}else toast('小さな数字を合体させて準備しよう。並べなおすこともできるよ。');}
function shuffle(){if(!canPlay())return;modal('盤面を並べなおす？','<p>新しい石を補充します。ライフ（スコアアタックは残り時間）を5秒使うよ。</p>',button('並べなおす','do-shuffle','primary')+button('やめる','close'));}
function act(action){if(!action)return;const [a,b,c]=action.split(':');switch(a){case'music-toggle':if(!soundtrack.unlocked||!soundtrack.settings.music||!soundtrack.settings.musicVolume){soundtrack.configure({music:true,musicVolume:soundtrack.settings.musicVolume||.45});soundtrack.unlock();}else soundtrack.configure({music:false});break;case'title':title();break;case'slots':slots();break;case'slot':openSlot(Number(b));break;case'delete-slot':requestDeleteSlot(Number(b));break;case'confirm-delete-slot':deleteSlot();break;case'map':map();break;case'workshop':workshop();break;case'assembly-replay':replayAssembly();break;case'custom':changeDesign(b,Number(c));break;case'stage':if(unlocked(Number(b)))start('story',Number(b));break;case'slow-retry':data.settings.slow=true;persist();start('story',Number(b));break;case'challenge':challenge(b);break;case'start':start(b,0,c);break;case'close':closeModal();break;case'resume-game':closeModal(false);briefStage(game,true);break;case'help':help();break;case'settings':settings();break;case'save-settings':data.settings.sound=soundtrack.settings.sound;data.settings.slow=$('#slow').checked;persist();closeModal();break;case'pause':pause();break;case'quit':modal('冒険をやめる？','<p>このステージの途中経過は保存されません。クリア済みの記録は残ります。</p>',button('やめる',game.mode==='story'?'map':'title')+button('つづける','close','primary'));break;case'op':if(canPlay()&&!game.path.length&&(b==='+'||game.stage.multiply)){game.op=b;updateHUD();}break;case'cancel':if(canPlay()){game.path=[];updateSelection();}break;case'confirm':commit();break;case'hint':hint();break;case'shuffle':shuffle();break;case'do-shuffle':if(game){soundtrack.play('shuffle');game.board=createBoard(game.stage);game.path=[];game.hint=[];if(game.mode==='score')game.remaining=Math.max(0,game.remaining-5);else game.life=Math.max(0,game.life-5);closeModal();updateBoard();updateHUD();if(game.life<=0||game.remaining<=0)finish(false);}break;case'flight':closeModal(false);conversation(epilogue,flight);break;case'prologue':conversation(prologue);break;case'install':requestInstall().then(result=>{if(result==='installed'){toast('ホーム画面から起動しています');return;}if(result==='instructions')modal('ホーム画面に追加','<p>iPhone・iPadでは、Safariの共有メニューから「ホーム画面に追加」を選んでね。</p><p>「Webアプリとして開く」が表示されたらオンにします。</p><p>Android・PCでは、ブラウザの「アプリをインストール」を選べます。</p><p class="muted">初回はネットにつないで開いてね。読み込み後はオフラインでも遊べます。<br>ブラウザ版とホーム画面版の記録が別になる端末があります。</p>',button('わかった！','close','primary'));});break;case'fullscreen':if(document.documentElement.requestFullscreen)document.documentElement.requestFullscreen().catch(()=>toast('この端末では全画面にできません'));else toast('横向きで遊んでね。Safariでは共有→ホーム画面に追加も使えます。');break;}}
app.addEventListener('click',e=>act(e.target.closest('[data-action]')?.dataset.action));dialog.addEventListener('click',e=>act(e.target.closest('[data-action]')?.dataset.action));dialog.addEventListener('cancel',e=>{e.preventDefault();if(game?.over)return;closeModal();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&game&&!game.over&&!game.paused)pause();});window.addEventListener('blur',()=>{if(game&&!game.over&&!game.paused)pause();});
function tick(now){const dt=(now-last)/1000;last=now;if(canPlay()&&!document.hidden){if(game.mode==='score'){game.remaining=Math.max(0,game.remaining-dt);if(game.remaining<=0)finish(false);}else{game.life=Math.max(0,game.life-dt*(game.mode==='story'&&data.settings.slow ? 0.5 : 1));if(game.life<=0)finish(false);}updateHUD();}requestAnimationFrame(tick);}
title();requestAnimationFrame(tick);

// All playback starts from a gesture. Hidden pages suspend the single audio context.
soundtrack.onChange=updateMusicButton;
for(const event of ['pointerdown','keydown'])document.addEventListener(event,e=>{if(e.target.closest?.('[data-action="music-toggle"]'))return;if(event==='keydown'&&(e.repeat||e.metaKey||e.ctrlKey||e.altKey))return;soundtrack.unlock();},{capture:true});
document.addEventListener('visibilitychange',()=>soundtrack.visibility(document.hidden));
window.addEventListener('pagehide',()=>soundtrack.visibility(true));
window.addEventListener('pageshow',()=>soundtrack.visibility(document.hidden));
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled||b.classList.contains('stone'))return;const action=b.dataset.action||'';if(/^(music-toggle|hint|do-shuffle|custom:|confirm)/.test(action))return;soundtrack.play(['title','slots','map','close'].includes(action)?'back':'click');});
dialog.addEventListener('input',e=>{const mappings={music:'music',sound:'sound','music-volume':'musicVolume','sound-volume':'soundVolume'},key=mappings[e.target.id];if(!key)return;const volume=e.target.type==='range',value=volume?Number(e.target.value)/100:e.target.checked;const ok=soundtrack.configure({[key]:value});if(volume)$('#'+(key==='musicVolume'?'music':'sound')+'-value').textContent=Math.round(value*100)+'%';const status=dialog.querySelector('.audio-save-status');status.textContent=ok?'音の設定を保存しました。':'このブラウザでは音の設定を保存できません。';if(key==='soundVolume'||key==='sound')soundtrack.play('select');});
document.addEventListener('miracle:chapter',e=>{soundtrack.duck('chapter',e.detail.open);if(e.detail.open&&!e.detail.clear)soundtrack.play('arrival');});
document.addEventListener('miracle:brief',e=>{soundtrack.duck('brief',e.detail.open);if(e.detail.open)soundtrack.play('intro');});
document.addEventListener('miracle:assembly',()=>soundtrack.play('assemble'));
